### ISSUE TITLE
mineimator on linux

### ISSUE THREAD

**Issue by NoName-hack-e** [stuffbydavid/Mine-imator#12]
I have been useing Mineimatior on Linux is kinda sucks cuz u have to use wine(a windows emultor like thing)
and it sucks cuz it has alot bug to run 
im a rust/c/java/c++/c# dev idk gml but i can lean it real quick 
i want to help mi Devs and @Nimikita  to make Mineimtor Pls DM me NoName_hacke_#9671 on Discrod

**Comment by Jossamations** [comment]
Unfortunately, Due to the circumstances relating to the Game Engine Mine-Imator is built on, Support is a little shotty with Linux. (Past Virtual Machines of Windows and such, At least from what I've heard and seen.)

Sorry for the inconvenience.

**Comment by 4wincode** [comment]
I'm very late replying to this but some pretty stable pre-releases for Mine-imator 2 are out and have support for Linux. https://www.mineimatorforums.com/index.php?/topic/88756-mine-imator-20-pre-release-4/
