### ISSUE TITLE
Hello, attempting to contact current developer :) Thank you

### ISSUE THREAD

**Issue by LeigerGaming** [stuffbydavid/Mine-imator#2]
Hey all,

Just wondering who the current developer for Mine-imator is? Commits indicate that David stopped working on it in 2019 and @Nimikita has done most updates since then. However, Nimi is no longer a member of the Discord server, leading me to believe that they are no longer supporting it?

Just trying to get in contact regarding a larger-scale code change I'd like to try on a forked version, which I'd submit as a pull request if I can get it working well.

Thank you.

**Comment by stuffbydavid** [comment]
Hey, @Nimikita's your guy. I'm no longer involved in this codebase.

**Comment by LeigerGaming** [comment]
No worries, thanks David. Someone got in touch with me and directed me to a different Discord server for Mine-imator.

Will attempt to contact Nimikita there.
