### ISSUE TITLE
Unusual bug: Everything slides back to initial positions without keyframes!

### ISSUE THREAD

**Issue by Xane123** [stuffbydavid/Mine-imator#3]
Today in Mine-imator, I was animating a cutscene for a potential Minecraft LP. Everything worked fine but after I added enough animation, I found a bug that's hard to explain. If the timeline is moved beyond the last actual keyframe, the camera and characters will slide back to the places they were at the beginning of the scene, then snapping back to where they are supposed to after that.

Basically, it's as if there was a keyframe placed on every object (and part) on the timeline that's identical to the first one on frame 0. If I change the first keyframe in any way, this "invisible keyframe" reflects those changes. I looked in the project file and can't find any keyframes that I didn't place, especially not where it snaps back to their proper places.

![WeirdCamGlitch1](https://user-images.githubusercontent.com/17244146/95669949-d6de0e00-0b53-11eb-84a6-3a7cd2cc6c0e.gif)
Here's a GIF of the glitch happening (though it only affects the camera here, the purple diamonds on the timeline.)

Since I've only encountered this oddity in the project I was making today, I've attached it below. Extract the files then load the project in Mine-imator. Move the timeline to where Mary (the girl) walks out of her house, and you will notice **the camera slides backward and Mary slides motionlessly back into the house through the door**. After a bit, the camera and Mary return to their intended places.

[ProjectWithOddBug.zip](https://github.com/stuffbydavid/Mine-imator/files/5360533/ProjectWithOddBug.zip)

(I just tested it again and it seems this glitch can be unpredictable; For me, the camera still went back to the start (despite not having a keyframe to do so) and Mary instantly switches into her initial walk stance.

Is there any way this can be fixed, or will there be a fix for this at all? @Nimikita, do you know what might be happening here? This glitch is unpredictable and could make animating hard if it affects a character...

Oh...and I would've posted this info on the forum, but email address verification is broken! (I'm Xane_MM if anyone reading this is an admin/moderator and would like to help me sign up without the broken email verification.)

**Comment by stuffbydavid** [comment]
Hi Xane123,
You have "Repeat the animation while animating keyframes seamlessly" option enabled. It's the button right below the movie export at the top. With this enabled the camera (or any object) will transition back to its first keyframe after its final keyframe. Quite useful for creating seamless loops but accidentally turning it on could cause some headaches...

The forum issue should be fixed now, can you check your mail again for a verification email?

Regards
David

**Comment by Xane123** [comment]
Ah, I was about to post about this in the forum but checked back here first. Good thing I did, as yep, I had that option on without knowing. Turning it off, the "problem" stopped! Now I can continue animating.

Also, I did check and yep, the forum sent the email but I assume it was probably invalid so I had another one sent and could verify my e-mail address so I'm now on the forum!

Thanks for the help, @stuffbydavid. (Also, must say, this is a really good program, impressive how it's made in Game Maker but doesn't even feel like it.)

**Comment by thedrawnsword** [comment]
> Today in Mine-imator, I was animating a cutscene for a potential Minecraft LP. Everything worked fine but after I added enough animation, I found a bug that's hard to explain. If the timeline is moved beyond the last actual keyframe, the camera and characters will slide back to the places they were at the beginning of the scene, then snapping back to where they are supposed to after that.
> 
> Basically, it's as if there was a keyframe placed on every object (and part) on the timeline that's identical to the first one on frame 0. If I change the first keyframe in any way, this "invisible keyframe" reflects those changes. I looked in the project file and can't find any keyframes that I didn't place, especially not where it snaps back to their proper places.
> 
> ![WeirdCamGlitch1](https://user-images.githubusercontent.com/17244146/95669949-d6de0e00-0b53-11eb-84a6-3a7cd2cc6c0e.gif) [ ![WeirdCamGlitch1](https://user-images.githubusercontent.com/17244146/95669949-d6de0e00-0b53-11eb-84a6-3a7cd2cc6c0e.gif) ](https://user-images.githubusercontent.com/17244146/95669949-d6de0e00-0b53-11eb-84a6-3a7cd2cc6c0e.gif) [ ](https://user-images.githubusercontent.com/17244146/95669949-d6de0e00-0b53-11eb-84a6-3a7cd2cc6c0e.gif) Here's a GIF of the glitch happening (though it only affects the camera here, the purple diamonds on the timeline.)
> 
> Since I've only encountered this oddity in the project I was making today, I've attached it below. Extract the files then load the project in Mine-imator. Move the timeline to where Mary (the girl) walks out of her house, and you will notice **the camera slides backward and Mary slides motionlessly back into the house through the door**. After a bit, the camera and Mary return to their intended places.
> 
> [ProjectWithOddBug.zip](https://github.com/stuffbydavid/Mine-imator/files/5360533/ProjectWithOddBug.zip)
> 
> (I just tested it again and it seems this glitch can be unpredictable; For me, the camera still went back to the start (despite not having a keyframe to do so) and Mary instantly switches into her initial walk stance.
> 
> Is there any way this can be fixed, or will there be a fix for this at all? @Nimikita, do you know what might be happening here? This glitch is unpredictable and could make animating hard if it affects a character...
> 
> Oh...and I would've posted this info on the forum, but email address verification is broken! (I'm Xane_MM if anyone reading this is an admin/moderator and would like to help me sign up without the broken email verification.)



> Ah, I was about to post about this in the forum but checked back here first. Good thing I did, as yep, I had that option on without knowing. Turning it off, the "problem" stopped! Now I can continue animating.
> 
> Also, I did check and yep, the forum sent the email but I assume it was probably invalid so I had another one sent and could verify my e-mail address so I'm now on the forum!
> 
> Thanks for the help, @stuffbydavid. (Also, must say, this is a really good program, impressive how it's made in Game Maker but doesn't even feel like it.)

wow thank you dude for this comment i had the same problem and without you i will never know the problem

**Comment by thedrawnsword** [comment]
wow thank you dude for this comment i had the same problem and without you i will never know the problem
