### ISSUE TITLE
Mine-imator Launch Speed VERY VERY SLOW!!!!!

### ISSUE THREAD

**Issue by AkarinLiu** [stuffbydavid/Mine-imator#4]

**Comment by Nimikita** [comment]
In the next major update, Mine-imator will use a newer GameMaker runtime engine which improves startup time. Here's a video I recorded a while back demonstrating the improvement. https://www.youtube.com/watch?v=ZI88MY0bDp8

**Comment by ghost** [comment]
Its probably your pc.
