### ISSUE TITLE
Linux (and MacOS) Platform Support

### ISSUE THREAD

**Issue by uqsme** [stuffbydavid/Mine-imator#5]
Hello David,

As you can see, Mine-imator is built in GMS2, which **could create executable for MacOS and Linux**. But unfortunately, we find that the software is only available in Windows version, and we had to run Mine-imator in a Wine container. I wonder if there is a plan to support Linux or MacOS.

Thanks
A Mine-imator User

**Comment by stuffbydavid** [comment]
Hi,
@Nimikita is the current developer of Mine-imator. You can best reach him via the Mine-imator forums for these questions.
As it looks now there are no plans for a Linux/Mac version since Mine-imator relies on Windows-specific GML and shader functionality.
